[adjust]
group = Runtime
title = Adjust
help = Adjust build settings. Runtime configuration lives in Lua.

ios_user_tracking_usage_description.type = string
ios_user_tracking_usage_description.default =
ios_user_tracking_usage_description.private = 1
ios_user_tracking_usage_description.label = iOS User Tracking Usage Description
